include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        BUNDLE: "gnome-clocks-dev.flatpak"
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.clocks.json"
        FLATPAK_MODULE: "gnome-clocks"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.clocksDevel"
    extends: ".flatpak"

nightly:
  extends: '.publish_nightly'

lint:
  image: "valalang/lint:latest"
  script:
    - io.elementary.vala-lint src

docs:
  image: "fedora:latest"
  script:
    - dnf install -y git valadoc vala meson glib2-devel gtk3-devel libhandy1-devel gsound-devel gnome-desktop3-devel libgweather-devel geoclue2-devel
    - meson -Ddocs=true _build
    - meson compile -C _build
    - rm -rf public
    - mv _build/docs public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'